### ISSUE TITLE
Add an angular conference info response

### ISSUE THREAD

**Issue by CamusAran** [Toxicable/ngbot#11]
AngularConnect
Angular Summit
ng-conf
ng-europe
...

A generic one that responds with a few upcoming conferences, and a conference specific response. Return location info, website link, countdown timer, etc.

Additional features:
Filter by continent
Filter by speaker
Filter by schedule item text (ex: animations, cli)

**Comment by Toxicable** [comment]
The way I see this would would be to implement it CLI style.
So commands might look like `angie events next` for the details on the next upcomming events.
Along with `angie events` for a list of upcomming events
And `angie events ng-conf` for a specific event

**Comment by Toxicable** [comment]
https://angular.io/events.html

**Comment by Toxicable** [comment]
inital version: 15cf2ad2a77fd245b9534f18dc33398ff940ecab
