### ISSUE TITLE
Name the bot!

### ISSUE THREAD

**Issue by Toxicable** [Toxicable/ngbot#16]
The current name: `angie` will not do. Therefore we will be renaming, the idea is to try make it a Pun or Paraday of Angular or Ng.
The name must conform to Angular's [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md)
Current suggestions have been: `penguin` and `kangaroo`

**Comment by lazarljubenovic** [comment]
Hint: The main idea is to have some pun on "angular", "ng", etc. Idea is `penguin` because it contains an "ng". Another one is "kangaroo".

**Comment by ghetolay** [comment]
ngRing

**Comment by Toxicable** [comment]
My vote is now on the name: `ng-bot`, `ngb` for short. I've renamed the repo to this name for now, just to see how it feels. Still open for suggestions
